# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Print:

    runs-on: ubuntu-latest

    steps:
    
    - name: doing checkout
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Running code
      run: |
        python3 app.py
